# Set the working directory to the folder containing the CSV files
setwd("C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents")



Rule0 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 0.csv", header = FALSE)
Rule1 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 1.csv", header = FALSE)
Rule2 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 2.csv", header = FALSE)
Rule3 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 3.csv", header = FALSE)
Rule4 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 4.csv", header = FALSE)
Rule5 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 5.csv", header = FALSE)
Rule6 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 6.csv", header = FALSE)
Rule7 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 7.csv", header = FALSE)
Rule8 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 8.csv", header = FALSE)
Rule9 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 9.csv", header = FALSE)
Rule10 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 10.csv", header = FALSE)
Rule11 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 11.csv", header = FALSE)
Rule12 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 12.csv", header = FALSE)
Rule13 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 13.csv", header = FALSE)
Rule14 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 14.csv", header = FALSE)
Rule15 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 15.csv", header = FALSE)
Rule16 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 16.csv", header = FALSE)
Rule17 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 17.csv", header = FALSE)
Rule18 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 18.csv", header = FALSE)
Rule19 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 19.csv", header = FALSE)
Rule20 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 20.csv", header = FALSE)
Rule21 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 21.csv", header = FALSE)
Rule22 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 22.csv", header = FALSE)
Rule23 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 23.csv", header = FALSE)
Rule24 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 24.csv", header = FALSE)
Rule25 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 25.csv", header = FALSE)
Rule26 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 26.csv", header = FALSE)
Rule27 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 27.csv", header = FALSE)
Rule28 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 28.csv", header = FALSE)
Rule29 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 29.csv", header = FALSE)
Rule30 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 30.csv", header = FALSE)
Rule31 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 31.csv", header = FALSE)
Rule32 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 32.csv", header = FALSE)
Rule33 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 33.csv", header = FALSE)
Rule34 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 34.csv", header = FALSE)
Rule35 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 35.csv", header = FALSE)
Rule36 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 36.csv", header = FALSE)
Rule37 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 37.csv", header = FALSE)
Rule38 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 38.csv", header = FALSE)
Rule39 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 39.csv", header = FALSE)
Rule40 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 40.csv", header = FALSE)
Rule41 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 41.csv", header = FALSE)
Rule42 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 42.csv", header = FALSE)
Rule43 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 43.csv", header = FALSE)
Rule44 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 44.csv", header = FALSE)
Rule45 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 45.csv", header = FALSE)
Rule46 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 46.csv", header = FALSE)
Rule47 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 47.csv", header = FALSE)
Rule48 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 48.csv", header = FALSE)
Rule49 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 49.csv", header = FALSE)
Rule50 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 50.csv", header = FALSE)
Rule51 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 51.csv", header = FALSE)
Rule52 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 52.csv", header = FALSE)
Rule53 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 53.csv", header = FALSE)
Rule54 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 54.csv", header = FALSE)
Rule55 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 55.csv", header = FALSE)
Rule56 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 56.csv", header = FALSE)
Rule57 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 57.csv", header = FALSE)
Rule58 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 58.csv", header = FALSE)
Rule59 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 59.csv", header = FALSE)
Rule60 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 60.csv", header = FALSE)
Rule61 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 61.csv", header = FALSE)
Rule62 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 62.csv", header = FALSE)
Rule63 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 63.csv", header = FALSE)
Rule64 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 64.csv", header = FALSE)
Rule65 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 65.csv", header = FALSE)
Rule66 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 66.csv", header = FALSE)
Rule67 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 67.csv", header = FALSE)
Rule68 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 68.csv", header = FALSE)
Rule69 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 69.csv", header = FALSE)
Rule70 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 70.csv", header = FALSE)
Rule71 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 71.csv", header = FALSE)
Rule72 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 72.csv", header = FALSE)
Rule73 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 73.csv", header = FALSE)
Rule74 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 74.csv", header = FALSE)
Rule75 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 75.csv", header = FALSE)
Rule76 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 76.csv", header = FALSE)
Rule77 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 77.csv", header = FALSE)
Rule78 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 78.csv", header = FALSE)
Rule79 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 79.csv", header = FALSE)
Rule80 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 80.csv", header = FALSE)
Rule81 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 81.csv", header = FALSE)
Rule82 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 82.csv", header = FALSE)
Rule83 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 83.csv", header = FALSE)
Rule84 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 84.csv", header = FALSE)
Rule85 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 85.csv", header = FALSE)
Rule86 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 86.csv", header = FALSE)
Rule87 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 87.csv", header = FALSE)
Rule88 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 88.csv", header = FALSE)
Rule89 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 89.csv", header = FALSE)
Rule90 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 90.csv", header = FALSE)
Rule91 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 91.csv", header = FALSE)
Rule92 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 92.csv", header = FALSE)
Rule93 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 93.csv", header = FALSE)
Rule94 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 94.csv", header = FALSE)
Rule95 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 95.csv", header = FALSE)
Rule96 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 96.csv", header = FALSE)
Rule97 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 97.csv", header = FALSE)
Rule98 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 98.csv", header = FALSE)
Rule99 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 99.csv", header = FALSE)
Rule100 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 100.csv", header = FALSE)
Rule101 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 101.csv", header = FALSE)
Rule102 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 102.csv", header = FALSE)
Rule103 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 103.csv", header = FALSE)
Rule104 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 104.csv", header = FALSE)
Rule105 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 105.csv", header = FALSE)
Rule106 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 106.csv", header = FALSE)
Rule107 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 107.csv", header = FALSE)
Rule108 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 108.csv", header = FALSE)
Rule109 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 109.csv", header = FALSE)
Rule110 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 110.csv", header = FALSE)
Rule111 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 111.csv", header = FALSE)
Rule112 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 112.csv", header = FALSE)
Rule113 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 113.csv", header = FALSE)
Rule114 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 114.csv", header = FALSE)
Rule115 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 115.csv", header = FALSE)
Rule116 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 116.csv", header = FALSE)
Rule117 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 117.csv", header = FALSE)
Rule118 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 118.csv", header = FALSE)
Rule119 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 119.csv", header = FALSE)
Rule120 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 120.csv", header = FALSE)
Rule121 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 121.csv", header = FALSE)
Rule122 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 122.csv", header = FALSE)
Rule123 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 123.csv", header = FALSE)
Rule124 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 124.csv", header = FALSE)
Rule125 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 125.csv", header = FALSE)
Rule126 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 126.csv", header = FALSE)
Rule127 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 127.csv", header = FALSE)
Rule128 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 128.csv", header = FALSE)
Rule129 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 129.csv", header = FALSE)
Rule130 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 130.csv", header = FALSE)
Rule131 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 131.csv", header = FALSE)
Rule132 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 132.csv", header = FALSE)
Rule133 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 133.csv", header = FALSE)
Rule134 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 134.csv", header = FALSE)
Rule135 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 135.csv", header = FALSE)
Rule136 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 136.csv", header = FALSE)
Rule137 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 137.csv", header = FALSE)
Rule138 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 138.csv", header = FALSE)
Rule139 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 139.csv", header = FALSE)
Rule140 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 140.csv", header = FALSE)
Rule141 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 141.csv", header = FALSE)
Rule142 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 142.csv", header = FALSE)
Rule143 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 143.csv", header = FALSE)
Rule144 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 144.csv", header = FALSE)
Rule145 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 145.csv", header = FALSE)
Rule146 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 146.csv", header = FALSE)
Rule147 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 147.csv", header = FALSE)
Rule148 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 148.csv", header = FALSE)
Rule149 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 149.csv", header = FALSE)
Rule150 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 150.csv", header = FALSE)
Rule151 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 151.csv", header = FALSE)
Rule152 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 152.csv", header = FALSE)
Rule153 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 153.csv", header = FALSE)
Rule154 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 154.csv", header = FALSE)
Rule155 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 155.csv", header = FALSE)
Rule156 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 156.csv", header = FALSE)
Rule157 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 157.csv", header = FALSE)
Rule158 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 158.csv", header = FALSE)
Rule159 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 159.csv", header = FALSE)
Rule160 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 160.csv", header = FALSE)
Rule161 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 161.csv", header = FALSE)
Rule162 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 162.csv", header = FALSE)
Rule163 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 163.csv", header = FALSE)
Rule164 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 164.csv", header = FALSE)
Rule165 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 165.csv", header = FALSE)
Rule166 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 166.csv", header = FALSE)
Rule167 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 167.csv", header = FALSE)
Rule168 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 168.csv", header = FALSE)
Rule169 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 169.csv", header = FALSE)
Rule170 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 170.csv", header = FALSE)
Rule171 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 171.csv", header = FALSE)
Rule172 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 172.csv", header = FALSE)
Rule173 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 173.csv", header = FALSE)
Rule174 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 174.csv", header = FALSE)
Rule175 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 175.csv", header = FALSE)
Rule176 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 176.csv", header = FALSE)
Rule177 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 177.csv", header = FALSE)
Rule178 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 178.csv", header = FALSE)
Rule179 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 179.csv", header = FALSE)
Rule180 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 180.csv", header = FALSE)
Rule181 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 181.csv", header = FALSE)
Rule182 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 182.csv", header = FALSE)
Rule183 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 183.csv", header = FALSE)
Rule184 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 184.csv", header = FALSE)
Rule185 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 185.csv", header = FALSE)
Rule186 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 186.csv", header = FALSE)
Rule187 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 187.csv", header = FALSE)
Rule188 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 188.csv", header = FALSE)
Rule189 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 189.csv", header = FALSE)
Rule190 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 190.csv", header = FALSE)
Rule191 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 191.csv", header = FALSE)
Rule192 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 192.csv", header = FALSE)
Rule193 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 193.csv", header = FALSE)
Rule194 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 194.csv", header = FALSE)
Rule195 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 195.csv", header = FALSE)
Rule196 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 196.csv", header = FALSE)
Rule197 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 197.csv", header = FALSE)
Rule198 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 198.csv", header = FALSE)
Rule199 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 199.csv", header = FALSE)
Rule200 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 200.csv", header = FALSE)
Rule201 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 201.csv", header = FALSE)
Rule202 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 202.csv", header = FALSE)
Rule203 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 203.csv", header = FALSE)
Rule204 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 204.csv", header = FALSE)
Rule205 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 205.csv", header = FALSE)
Rule206 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 206.csv", header = FALSE)
Rule207 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 207.csv", header = FALSE)
Rule208 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 208.csv", header = FALSE)
Rule209 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 209.csv", header = FALSE)
Rule210 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 210.csv", header = FALSE)
Rule211 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 211.csv", header = FALSE)
Rule212 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 212.csv", header = FALSE)
Rule213 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 213.csv", header = FALSE)
Rule214 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 214.csv", header = FALSE)
Rule215 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 215.csv", header = FALSE)
Rule216 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 216.csv", header = FALSE)
Rule217 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 217.csv", header = FALSE)
Rule218 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 218.csv", header = FALSE)
Rule219 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 219.csv", header = FALSE)
Rule220 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 220.csv", header = FALSE)
Rule221 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 221.csv", header = FALSE)
Rule222 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 222.csv", header = FALSE)
Rule223 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 223.csv", header = FALSE)
Rule224 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 224.csv", header = FALSE)
Rule225 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 225.csv", header = FALSE)
Rule226 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 226.csv", header = FALSE)
Rule227 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 227.csv", header = FALSE)
Rule228 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 228.csv", header = FALSE)
Rule229 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 229.csv", header = FALSE)
Rule230 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 230.csv", header = FALSE)
Rule231 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 231.csv", header = FALSE)
Rule232 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 232.csv", header = FALSE)
Rule233 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 233.csv", header = FALSE)
Rule234 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 234.csv", header = FALSE)
Rule235 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 235.csv", header = FALSE)
Rule236 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 236.csv", header = FALSE)
Rule237 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 237.csv", header = FALSE)
Rule238 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 238.csv", header = FALSE)
Rule239 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 239.csv", header = FALSE)
Rule240 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 240.csv", header = FALSE)
Rule241 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 241.csv", header = FALSE)
Rule242 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 242.csv", header = FALSE)
Rule243 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 243.csv", header = FALSE)
Rule244 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 244.csv", header = FALSE)
Rule245 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 245.csv", header = FALSE)
Rule246 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 246.csv", header = FALSE)
Rule247 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 247.csv", header = FALSE)
Rule248 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 248.csv", header = FALSE)
Rule249 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 249.csv", header = FALSE)
Rule250 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 250.csv", header = FALSE)
Rule251 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 251.csv", header = FALSE)
Rule252 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 252.csv", header = FALSE)
Rule253 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 253.csv", header = FALSE)
Rule254 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 254.csv", header = FALSE)
Rule255 = read.csv(file = "C:\\Users\\conor\\OneDrive - University College Cork\\FYP\\ECA Lyapunov Exponents\\Lambda, Rule 255.csv", header = FALSE)



for (i in 1:50)
  for (j in 1:500)
    if (Rule7[i,j] == "-∞")
      Rule7[i,j] = -1


max(as.numeric(Rule7[,500]), na.rm = TRUE)
median(as.numeric(Rule7[,500]), na.rm = TRUE)
min(as.numeric(Rule7[,500]), na.rm = TRUE)









for (i in 1:50)
  for (j in 1:500)
    if (Rule100[i,j] == '#NAME?')
      Rule100[i,j] = NA

plot(y = Rule100[1,seq(1,500,1)], x = seq(1,500,1), type = 'p', main = "Rule 100 Lyapunov Exponents", xlab = "Iterations", ylab = "Lambda")
for (i in 2:50){
  points(Rule100[i,seq(1,500,1)], x = seq(1,500,1), type = 'p')
}


for (i in 1:50)
  for (j in 1:500)
    if (Rule110[i,j] == '#NAME?')
      Rule110[i,j] = NA

plot(y = Rule110[1,seq(1,500,1)], x = seq(1,500,1), type = 'p', main = "Rule 110 Lyapunov Exponents", xlab = "Iterations", ylab = "Lambda")
for (i in 2:50){
  points(Rule110[i,seq(1,500,1)], x = seq(1,500,1), type = 'p')
}


for (i in 1:50)
  for (j in 1:500)
    if (Rule124[i,j] == '#NAME?')
      Rule124[i,j] = NA

plot(y = Rule124[1,seq(1,500,2)], x = seq(1,500,2), type = 'p', main = "Rule 124 Lyapunov Exponents", xlab = "Iterations", ylab = "Lambda")
for (i in 2:50){
  points(Rule124[i,seq(1,500,2)], x = seq(1,500,2), type = 'p')
}





for (i in 1:50)
  for (j in 1:500)
    if (Rule150[i,j] == '#NAME?')
      Rule150[i,j] = NA

plot(y = Rule150[1,seq(1,500,1)], x = seq(1,500,1), type = 'p', main = "Rule 150 Lyapunov Exponents", xlab = "Iterations", ylab = "Lambda")
for (i in 2:50){
  points(Rule150[i,seq(1,500,1)], x = seq(1,500,1), type = 'p')
}




for (i in 1:50)
  for (j in 1:500)
    if (Rule60[i,j] == '#NAME?')
      Rule60[i,j] = NA

plot(y = Rule60[1,seq(1,500,1)], x = seq(1,500,1), type = 'p', main = "Rule 60 Lyapunov Exponents", xlab = "Iterations", ylab = "Lambda")
for (i in 2:50){
  points(Rule60[i,seq(1,500,1)], x = seq(1,500,1), type = 'p')
}





for (i in 1:50)
  for (j in 1:500)
    if (Rule0[i,j] == '#NAME?')
      Rule0[i,j] = NA

plot(y = Rule0[1,seq(1,500,1)], x = seq(1,500,1), type = 'p', main = "Rule 0 Lyapunov Exponents", xlab = "Iterations", ylab = "Lambda")
for (i in 2:50){
  points(Rule0[i,seq(1,500,1)], x = seq(1,500,1), type = 'p')
}








